name: 'Setup Node.js'
description: 'Setup Node.js, cache and install dependencies. Requires checkout to be run first.'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22.22.0'

runs:
  using: 'composite'
  steps:
    - name: Use Node.js v${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://npm.pkg.github.com'

    - name: Cache node modules
      id: cache-node
      uses: actions/cache@v5
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-node.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
