# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    registries:
      - npm-github
    schedule:
      interval: daily
    versioning-strategy: increase
    groups:
      designsystemet:
        patterns:
          - '@navikt/ds*'
          - '@navikt/aksel*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      sanity:
        patterns:
          - 'sanity'
          - '@sanity/vision'

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}
    replaces-base: true
