# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Update GitHub action
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Update npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - registries:
      npm-github:
        type: npm-registry
        url: https://npm.pkg.github.com
        token: ${{ secrets.READER_TOKEN }}
        replaces-base: true
