apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjonskalkulator-frontend-{{ deployment_name  }}
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
  annotations:
    nais.io/run-as-user: "101" # nginx
spec:
  image: "{{ image }}"
  ingresses:
    - https://{{ deployment_name }}.adhoc-pensjonskalkulator.ekstern.dev.nav.no/pensjon/kalkulator
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  frontend:
    generatedConfig:
      mountPath: /app/src/nais.js
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/ping
        - /pensjon/kalkulator
        - /pensjon/kalkulator/login
        - /pensjon/kalkulator/personopplysninger
        - /pensjon/kalkulator/assets/*
        - /pensjon/kalkulator/api/status
        - /pensjon/kalkulator/api/feature/*
        - /pensjon/kalkulator/src/*
        - /pensjon/kalkulator/v3/api-docs/current
  accessPolicy:
    outbound:
      rules:
        - application: pensjonskalkulator-backend
  env:
    - name: "PENSJONSKALKULATOR_BACKEND"
      value: "https://pensjonskalkulator-backend.intern.dev.nav.no"
    - name: "TOKEN_X_OBO_AUDIENCE"
      value: "dev-gcp:pensjonskalkulator:pensjonskalkulator-backend"
