apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjonskalkulator-frontend-sanity
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
  annotations:
    nais.io/run-as-user: "1001" # nginx
    nais.io/read-only-file-system: "false"
spec:
  image: "{{ image }}"
  ingresses:
    - https://pensjonskalkulator-sanity.ansatt.dev.nav.no
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  accessPolicy:
    outbound:
      external:
        - host: api.sanity.io
        - host: 948n95rd.api.sanity.io
        - host: apicdn.sanity.io
        - host: 948n95rd.apicdn.sanity.io
        - host: cdn.sanity.io
