apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjonskalkulator-frontend-sandbox
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
  annotations:
    nais.io/run-as-user: "101" # nginx
spec:
  image: "{{ image }}"
  ingresses:
    - https://sandbox.ekstern.dev.nav.no/pensjon/kalkulator
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  frontend:
    generatedConfig:
      mountPath: /app/src/nais.js
  prometheus:
    enabled: true
    path: /metrics
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      level: idporten-loa-substantial
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/ping
        - /pensjon/kalkulator
        - /pensjon/kalkulator/login
        - /pensjon/kalkulator/personopplysninger
        - /pensjon/kalkulator/forbehold
        - /pensjon/kalkulator/assets/*
        - /pensjon/kalkulator/api/status
        - /pensjon/kalkulator/api/feature/*
        - /pensjon/kalkulator/src/*
        - /pensjon/kalkulator/v3/api-docs/current
  accessPolicy:
    outbound:
      rules:
        - application: pensjonskalkulator-backend
      external:
        - host: pensjonskalkulator-unleash-api.nav.cloud.nais.io
    inbound:
      rules:
        - application: wonderwalled-idporten # only in dev
          namespace: aura
  env:
    - name: "PENSJONSKALKULATOR_BACKEND"
      value: "http://pensjonskalkulator-backend"
    - name: "TOKEN_X_OBO_AUDIENCE"
      value: "dev-gcp:pensjonskalkulator:pensjonskalkulator-backend"
    - name: "DETALJERT_KALKULATOR_URL"
      value: "https://pensjon-pselv-q2-gcp.ansatt.dev.nav.no/pselv/simulering.jsf?simpleMode=true"
  envFrom:
    - secret: pensjonskalkulator-frontend-unleash-api-token
