import globalClassNames from '../../style.d'
declare const classNames: typeof globalClassNames & {
  readonly section: 'section'
  readonly info: 'info'
  readonly buttonRow: 'buttonRow'
  readonly buttonRowElement: 'buttonRowElement'
  readonly buttonRowElement__Right: 'buttonRowElement__Right'
  readonly infoIcon: 'infoIcon'
  readonly infoText: 'infoText'
  readonly tooltip: 'tooltip'
  readonly tooltipTable: 'tooltipTable'
  readonly tooltipLine: 'tooltipLine'
  readonly tooltipTableHeaderCell: 'tooltipTableHeaderCell'
  readonly tooltipTableHeaderCell__left: 'tooltipTableHeaderCell__left'
  readonly tooltipTableHeaderCell__right: 'tooltipTableHeaderCell__right'
  readonly tooltipTableCell: 'tooltipTableCell'
  readonly tooltipTableCell__right: 'tooltipTableCell__right'
  readonly tooltipTableCellDot: 'tooltipTableCellDot'
  readonly 'highcharts-tooltip-container': 'highcharts-tooltip-container'
  readonly 'highcharts-scrollable-mask': 'highcharts-scrollable-mask'
}
export = classNames
