name: Build, test, push, deploy to dev-gcp

on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository }}/pensjonskalkulator-frontend:${{ github.sha }}
    steps:
      - name: Use Node.js v19.6.0
        uses: actions/setup-node@v3
        with:
          node-version: '19.6.0'
          registry-url: 'https://npm.pkg.github.com'
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build application
        env:
          VITE_DEKORATOREN_URL: 'https://dekoratoren.dev.nav.no'
        run: npm run build
      - name: Test application
        run: npm run test
      - name: Build Docker image dev-gcp
        run: |
          docker build -f .docker/Dockerfile -t ${IMAGE} .
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yml
