name: Build, test, push, deploy to dev-gcp

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js v19.6.0
        uses: actions/setup-node@v3
        with:
          node-version: '19.6.0'
          registry-url: 'https://npm.pkg.github.com'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build application
        env:
          VITE_DEKORATOREN_URL: 'https://dekoratoren.dev.nav.no'
        run: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          if-no-files-found: error
          path: dist

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run unit tests
        run: npm run test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage

  run-integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Install cypress
        run: npx cypress install

      - name: Run integration tests
        run: npm run cy:test

      - name: Archive Cypress artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: videos
          path: cypress/videos

  deploy-to-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    needs: [ run-unit-tests, run-integration-tests ]
    env:
      IMAGE: ghcr.io/${{ github.repository }}/pensjonskalkulator-frontend:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Build Docker image dev-gcp
        run: |
          docker build -f .docker/Dockerfile -t ${IMAGE} .

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}

      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yml
